In [2]:
import numpy as np
import pandas as pd

# Creating arrays in numpy
**Arrays can be created using numpy**

*1. Ranks*

*2. Tuples*


## Ranks arrays

In [3]:
# Rank 1 arrays
rank1_arr=np.array([1,2,3])
print(rank1_arr)
# Rank 2 arrays
rank2_arr=np.array([[1,2,3],[4,5,6]])
print(rank2_arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]


## Tuples

In [4]:
tup_arr=np.array((1,2,3))
print(tup_arr)

[1 2 3]


# Accesing values in arrays
**The number of dimensions specify the number indices used to access values in an array**

In [5]:
arr1=np.array([4,3,5,54,43])
arr2=np.array([[13,542,6465],[43,662,54]])
arr3=np.array([[23,564,56,75],[24,65,75,76]])

 ## To know the number of dimensions in an array

In [6]:
arrayone=arr1.ndim
arraytwo=arr2.ndim
arraythree=arr3.ndim
print(arrayone)
print(arraytwo)
print(arraythree)

1
2
2


## Accessing the arrays

In [7]:
# Access 5 in arr1
print(arr1[2])

5


In [8]:
# access 54 in arr2
print(arr2[1,2])

54


## Shape function

In [9]:
arr1.shape


(5,)

In [10]:
arr2.shape


(2, 3)

# Common functions

## np.arange()

In [11]:
this_arr=np.arange(100)
print (this_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [12]:
that_arr=np.arange(3,61,3)
print(that_arr)
#an rray that starts from 3, to 60 at a 3 interval

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60]


## np.random

### np.random.permutation()

In [13]:
rand_arr=np.random.permutation(range(2,9,2))
print(rand_arr)

[4 2 8 6]


### np.random.randint()

In [14]:
rand_int=np.random.randint(1,9000)
print(rand_int)

2289
